# -*- coding: utf-8 -*-
# vim: ft=yaml
---
###############################################################################
# Define all YAML node anchors
###############################################################################
.node_anchors:
  # `stage`
  stage_test: &stage_test 'test'
  # `image`
  image_dindruby: &image_dindruby 'myii/ssf-dind-ruby-bionic:1_2.5.1'
  # `services`
  services_docker_dind: &services_docker_dind
    - 'docker:dind'
  # `variables`
  # https://forum.gitlab.com/t/gitlab-com-ci-caching-rubygems/5627/3
  # https://bundler.io/v1.16/bundle_config.html
  variables_bundler: &variables_bundler
    BUNDLE_CACHE_PATH: '${CI_PROJECT_DIR}/.cache/bundler'
    BUNDLE_WITHOUT: 'production'
  # `cache`
  cache_bundler: &cache_bundler
    key: '${CI_JOB_STAGE}'
    paths:
      - '${BUNDLE_CACHE_PATH}'

###############################################################################
# Define stages and global variables
###############################################################################
stages:
  - *stage_test
variables:
  DOCKER_DRIVER: 'overlay2'

###############################################################################
# Define `test` template
###############################################################################
.test_instance:
  stage: *stage_test
  image: *image_dindruby
  services: *services_docker_dind
  variables: *variables_bundler
  cache: *cache_bundler
  before_script:
    - 'bundle config set path "${BUNDLE_CACHE_PATH}"'
    - 'bundle config set without "${BUNDLE_WITHOUT}"'
    - 'bundle install --with docker --without opennebula ec2 windows vagrant'
    - 'pip3 install -U pip'
    - 'pip3 install -r tests/requirements.txt'
  script:
    # yamllint disable-line rule:line-length
    - 'bundle exec kitchen create -l debug "${DOCKER_ENV_CI_JOB_NAME}" || bundle exec kitchen create -l debug "${DOCKER_ENV_CI_JOB_NAME}"'
    - 'bundle exec kitchen verify -l debug "${DOCKER_ENV_CI_JOB_NAME}"'
    - 'bundle exec kitchen destroy -l debug "${DOCKER_ENV_CI_JOB_NAME}"'

###############################################################################
# `test` stage: each instance below uses the `test` template above
###############################################################################
py3-git-3001-opensuse-tumbleweed: {extends: '.test_instance'}
py3-git-3002-opensuse-tumbleweed: {extends: '.test_instance'}
py3-git-master-opensuse-tumbleweed: {extends: '.test_instance'}
latest-opensuse-tumbleweed: {extends: '.test_instance'}
