---
name: 'Kitchen Vagrant (FreeBSD, OpenBSD & Windows)'
'on': ['push', 'pull_request']

env:
  KITCHEN_LOCAL_YAML: 'kitchen.vagrant.yml'

jobs:
  test:
    runs-on: 'macos-10.15'
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        instance:
          # - py3-git-3000-freebsd-122
          # - py3-git-3000-freebsd-114
          # - py3-git-3000-openbsd-68
          # - py3-git-3001-freebsd-122
          # - py3-git-3001-freebsd-114
          # - py3-git-3001-openbsd-68
          # - py3-git-3002-freebsd-122
          # - py3-git-3002-freebsd-114
          # - py3-git-3002-openbsd-68
          # - py3-git-master-freebsd-122
          # - py3-git-master-freebsd-114
          # - py3-git-master-openbsd-68
          - latest-freebsd-122
          - latest-freebsd-114
          - latest-openbsd-68
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v2'
      - name: 'Set up Bundler cache'
        uses: 'actions/cache@v1'
        with:
          path: 'vendor/bundle'
          key: "${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}"
          restore-keys: "${{ runner.os }}-gems-"
      - name: 'Run Bundler'
        run: |
          ruby --version
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: 'Set up Python 3.7'
        uses: 'actions/setup-python@v1'
        with:
          python-version: '3.7'
      - name: 'Install Python Dependencies'
        run: |
          pip install -U pip
          pip install -r tests/requirements.txt
      - name: 'Run Test Kitchen'
        run: 'bundle exec kitchen test ${{ matrix.instance }}'
